[theme]
primaryColor = "#0A4174"
backgroundColor = "#F3F7FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#001D39"
font = "sans serif"
base = "light"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
